"use client";
import { useEffect, useState } from "react";
import DayFourLanding, { type DayFourSection } from "./DayFourLanding";
import DebateExperience from "./DebateExperience";
import TheoryStudio from "./TheoryStudio";
import VideoSlides from "./VideoSlides";
import ScenarioSimulator, { type SimScenario } from "./ScenarioSimulator";
import { SectionNav, type Slide } from "./shared";

const theorySlides: Slide[] = [
 { src: "/slides/dia4/slide-01.jpg", alt: "Sistemas Mecánicos — Portada del Módulo IV" },
 { src: "/slides/dia4/slide-02.jpg", alt: "De la Energía al Proceso" },
 { src: "/slides/dia4/slide-03.jpg", alt: "El Motor Como Elemento Impulsor" },
 { src: "/slides/dia4/slide-04.jpg", alt: "Acoplamientos: Rígidos y Flexibles" },
 { src: "/slides/dia4/slide-05.jpg", alt: "Desalineación Paralela y Angular" },
 { src: "/slides/dia4/slide-06.jpg", alt: "Reductores de Velocidad" },
 { src: "/slides/dia4/slide-07.jpg", alt: "Bombas Centrífugas" },
 { src: "/slides/dia4/slide-08.jpg", alt: "Cavitación en Bombas" },
 { src: "/slides/dia4/slide-09.jpg", alt: "Transportadores y Ventiladores Industriales" },
 { src: "/slides/dia4/slide-10.jpg", alt: "Lubricación: Más No Es Mejor" },
 { src: "/slides/dia4/slide-11.jpg", alt: "La Tendencia Importa Más Que el Último Número" },
 { src: "/slides/dia4/slide-12.jpg", alt: "Cierre del Módulo IV" },
];

type Tab = "overview" | DayFourSection;

const module4Scenarios: SimScenario[] = [
 { code: "SIM4-01", title: "Reductor con fuga y ruido", situation: "Un reductor de velocidad presenta una fuga de lubricante visible en la carcasa y ruido anormal durante la operación.", steps: [
   { prompt: "¿Cómo interpretas la fuga de lubricante?", options: ["Es solo un problema estético, no requiere atención inmediata.", "Puede ser evidencia de deterioro de un sello, problemas de montaje o presión interna.", "Significa que el reductor tiene demasiado lubricante y hay que vaciarlo.", "Es normal en todos los reductores y no debe registrarse."], answer: 1, feedback: "Una fuga de lubricante no debe interpretarse solo como estética: puede ser evidencia de deterioro de un sello, problemas de montaje, presión interna u otra condición que requiere investigación." },
   { prompt: "¿Qué inspeccionarías primero, antes de abrir el reductor?", options: ["Condición general, fugas, fijaciones y evidencia de temperatura, sin desmontar.", "Directamente desarmar el reductor para ver el interior.", "Cambiar el lubricante y ver si el ruido desaparece.", "Aumentar la velocidad para escuchar mejor el ruido."], answer: 0, feedback: "La inspección inicial se hace observando sin desmontar: condiciones generales, fugas, fijaciones, guardas, contaminación y evidencia de temperatura." },
   { prompt: "El ruido y la fuga aparecieron poco después de un mantenimiento reciente. ¿Qué hipótesis priorizas?", options: ["Casualidad, no tiene relación con el mantenimiento.", "Posible condición de montaje o alineación introducida durante el mantenimiento reciente.", "Falla de fábrica del reductor, sin relación con el servicio.", "El operador está exagerando el problema."], answer: 1, feedback: "Cuando el síntoma aparece justo después de una intervención, una hipótesis prioritaria razonable es que el propio mantenimiento haya introducido una condición de montaje o alineación deficiente." },
 ] },
 { code: "SIM4-02", title: "Banda desviada en un transportador", situation: "Producción reporta que la banda de un transportador se está desviando hacia un lado y roza contra la estructura.", steps: [
   { prompt: "¿Qué NO deberías hacer primero?", options: ["Detener el proceso de forma segura antes de inspeccionar.", "Ajustar a ciegas la tensión de la banda mientras está en movimiento, sin evaluar la causa.", "Revisar la alineación de los rodillos.", "Consultar si hubo cambios recientes de carga o mantenimiento."], answer: 1, feedback: "Ajustar la tensión sin evaluar la causa (alineación, rodillos, carga, contaminación) es una reacción reactiva que puede no resolver el problema y añade riesgo si se hace con el equipo en movimiento." },
   { prompt: "¿Qué causas debes considerar para una banda desviada?", options: ["Solo la tensión de la banda.", "Alineación, condición de rodillos, tensión, distribución de carga, contaminación y condiciones estructurales.", "Únicamente el color de la banda.", "Solo la velocidad del motor."], answer: 1, feedback: "Una banda desviada puede deberse a alineación, condición de rodillos, tensión, distribución de carga, contaminación o condiciones estructurales — no a una sola causa aislada." },
   { prompt: "Encuentras que un rodillo está desalineado respecto a los demás. ¿Cuál es el siguiente paso correcto?", options: ["Cambiar la banda completa, ya que es lo más visible.", "Corregir la alineación del rodillo y verificar que la banda deje de desviarse.", "Aumentar la tensión general de la banda para compensar.", "Ignorarlo si la producción no se ha detenido."], answer: 1, feedback: "Corregir la causa identificada (el rodillo desalineado) y verificar que el síntoma desaparezca es la secuencia correcta — no reemplazar el componente más visible sin relación directa con la causa." },
 ] },
 { code: "SIM4-03", title: "Ventilador con vibración", situation: "Un ventilador industrial de extracción presenta vibración notablemente mayor que en inspecciones anteriores.", steps: [
   { prompt: "¿Qué NO puedes asumir de inmediato solo por la vibración?", options: ["Que existe una condición mecánica que debe investigarse.", "Que definitivamente es desbalance del impulsor.", "Que conviene registrar el hallazgo.", "Que debe compararse con el historial de vibración."], answer: 1, feedback: "Vibración elevada no significa automáticamente desbalance; debe diferenciarse de desalineación, holguras, problemas de rodamientos u otras fuentes antes de concluir." },
   { prompt: "Al inspeccionar, encuentras acumulación de material sobre las aspas del impulsor. ¿Qué relación tiene con la vibración?", options: ["Ninguna, son problemas independientes.", "Puede alterar la distribución de masa del impulsor y contribuir al desbalance.", "Solo afecta la eficiencia, no la vibración.", "Es un problema puramente estético."], answer: 1, feedback: "Una condición aparentemente pequeña, como acumulación de material sobre el impulsor, puede alterar su distribución de masa y contribuir a un problema de desbalance." },
   { prompt: "¿Qué harías antes de decidir balancear el impulsor?", options: ["Balancear de inmediato sin más verificación.", "Limpiar la acumulación y verificar si la vibración vuelve a un nivel normal antes de asumir que se requiere balanceo.", "Cambiar el ventilador completo.", "Aumentar la velocidad para \"sacudir\" el material acumulado."], answer: 1, feedback: "Debe corregirse primero la condición identificada (limpieza) y verificar el efecto antes de escalar a una intervención mayor como el balanceo del impulsor." },
 ] },
 { code: "SIM4-04", title: "Alineación después de un mantenimiento", situation: "Un conjunto motor-bomba fue realineado durante un mantenimiento programado. Dos semanas después, el técnico nota temperatura ligeramente elevada en un rodamiento.", steps: [
   { prompt: "¿Qué método da una medición cuantitativa confiable de la alineación, más allá de la inspección visual?", options: ["El método visual con una regla es suficiente para cualquier caso.", "Indicadores de carátula o un sistema de alineación láser.", "Solo con escuchar el ruido del motor.", "Preguntar al técnico que hizo el mantenimiento si quedó bien."], answer: 1, feedback: "El método visual tiene limitaciones importantes para alineación de precisión; los indicadores de carátula y los sistemas láser permiten mediciones cuantitativas confiables." },
   { prompt: "¿Qué relación existe entre desalineación y la temperatura elevada que reporta el técnico?", options: ["Ninguna relación posible.", "Una desalineación puede generar fuerzas adicionales que se convierten en cargas sobre rodamientos y aumento de temperatura.", "La temperatura solo depende de la carga eléctrica.", "La temperatura elevada siempre indica un problema del motor, no del acoplamiento."], answer: 1, feedback: "Una condición de desalineación puede generar fuerzas adicionales sobre el sistema y contribuir a cargas adicionales sobre rodamientos, deterioro de sellos y aumento de temperatura." },
   { prompt: "Antes de repetir la alineación de precisión, ¿qué deberías verificar?", options: ["Nada más, se repite la alineación directamente.", "La condición mecánica de las bases y la fijación.", "El color de la pintura de la base.", "Que el clima sea favorable."], answer: 1, feedback: "No tendría sentido efectuar una alineación de precisión sobre una máquina con una base mecánicamente deficiente o con otros problemas no corregidos; estas condiciones deben revisarse antes." },
 ] },
 { code: "SIM4-05", title: "VFD en alarma con resistencia mecánica", situation: "Un transportador recibe la orden de arranque, el VFD recibe la señal RUN e intenta arrancar el motor, pero aparece una alarma de sobrecorriente y el transportador presenta resistencia mecánica anormal al giro.", steps: [
   { prompt: "¿Qué significa la alarma de sobrecorriente del VFD por sí sola?", options: ["Que el variador está dañado y debe reemplazarse.", "Que el motor está pidiendo más corriente de la esperada; el código indica una condición detectada, no necesariamente su causa.", "Que el problema es definitivamente eléctrico.", "Que basta con reiniciar el VFD para que el problema desaparezca."], answer: 1, feedback: "Código de falla ≠ causa raíz. El VFD indica qué condición detectó (sobrecorriente), no necesariamente qué componente la originó." },
   { prompt: "Dado que también hay resistencia mecánica anormal al giro, ¿hacia dónde dirige esto tu investigación?", options: ["Exclusivamente hacia la programación del VFD.", "Hacia la cadena mecánica: motor, transmisión y carga, ya que una condición mecánica puede manifestarse como una alarma eléctrica.", "Hacia el cableado de red del PLC.", "Ningún lado en particular, es aleatorio."], answer: 1, feedback: "Una condición mecánica puede manifestarse como una alarma eléctrica. La ruta de investigación correcta continúa hacia VFD → motor → transmisión → carga." },
   { prompt: "¿Qué NO deberías hacer para \"solucionar\" el problema rápido?", options: ["Investigar la cadena mecánica antes de intervenir.", "Aumentar el límite de corriente en los parámetros del VFD para que deje de dispararse, sin investigar la causa.", "Documentar la alarma y la condición mecánica encontrada.", "Verificar si el transportador tiene alguna obstrucción."], answer: 1, feedback: "Modificar un parámetro del VFD para \"evitar\" la alarma sin comprender su función ni investigar la causa puede ocultar una condición peligrosa y dificultar el diagnóstico posterior." },
 ] },
];

const module4Debates = [
 { code: "D4-01", title: "Transportador CT-205: vibración, ruido y un acoplamiento desgastado.", case: "Producción reporta vibración mayor a la habitual y ruido en la zona motor-reductor del transportador CT-205. La inspección encuentra temperatura elevada en un apoyo, el elemento flexible del acoplamiento con desgaste visible, y un mantenimiento realizado dos semanas antes.", prompt: "Frente a la pregunta \"¿qué componente cambiarían?\", ¿qué deberían responder primero? ¿El desgaste visible ya es suficiente para ordenar el reemplazo?", lenses: ["Evidencia vs. causa raíz", "Historial de mantenimiento reciente", "Riesgo de reincidencia", "Ruta de hipótesis antes de intervenir"], options: ["Cambiar de inmediato el elemento flexible del acoplamiento porque el desgaste es visible.", "Reconocer que todavía no hay evidencia suficiente y formular hipótesis (alineación, lubricación, montaje) antes de decidir qué cambiar.", "Aumentar la velocidad de la banda para confirmar si el ruido desaparece."], answer: 1, feedback: "El objetivo no es encontrar rápido una pieza que cambiar, sino identificar por qué se está deteriorando. Reemplazar el elemento sin investigar la causa —posible desalineación tras el mantenimiento reciente— hace muy probable que la falla reaparezca." },
 { code: "D4-02", title: "Corriente elevada en el motor de un transportador sobrecargado.", case: "El motor de un transportador registra una corriente superior a la habitual. El equipo de mantenimiento eléctrico revisa protecciones y conexiones sin encontrar anomalías, mientras producción reporta que la banda transporta más material del acostumbrado esta semana.", prompt: "¿Una corriente elevada siempre indica una falla eléctrica? ¿Qué relación existe entre carga mecánica y comportamiento eléctrico del motor?", lenses: ["Relación torque-corriente", "Condición mecánica vs. eléctrica", "Evidencia del cambio de proceso", "Riesgo de intervenir el componente equivocado"], options: ["Concluir que el motor está fallando y solicitar su reemplazo inmediato.", "Correlacionar la corriente elevada con el incremento de carga mecánica reportado, ya que mayor carga demanda mayor torque y por tanto mayor corriente.", "Subir el ajuste de la protección térmica para evitar que el motor se detenga."], answer: 1, feedback: "Mayor carga mecánica → mayor demanda de torque → modificación de la corriente del motor. Encontrar corriente elevada no demuestra automáticamente una falla eléctrica; primero debe descartarse una causa mecánica o de proceso." },
 { code: "D4-03", title: "Una bomba vibra: ¿es cavitación?", case: "Un operador reporta que una bomba centrífuga \"hace ruido\" y parece vibrar más de lo normal. Un compañero afirma de inmediato: \"seguro está cavitando\", sin haber revisado nada más.", prompt: "¿Es correcto asumir cavitación solo por el ruido? ¿Qué otras familias de causas deben descartarse antes de confirmar esa hipótesis?", lenses: ["Causas mecánicas de vibración", "Causas hidráulicas de vibración", "Causas estructurales de vibración", "Secuencia síntoma → hipótesis → evidencia"], options: ["Aceptar la hipótesis de cavitación y reducir el flujo de la bomba sin más verificación.", "Reconocer que el ruido es un síntoma compatible con causas mecánicas, hidráulicas o estructurales, y verificar succión, alineación, rodamientos y sujeción antes de confirmar cavitación.", "Detener la bomba de forma permanente hasta que alguien más experimentado la revise, sin registrar ninguna evidencia."], answer: 1, feedback: "VIBRACIÓN ≠ DIAGNÓSTICO. El ruido puede originarse en condiciones mecánicas (desalineación, desbalance, rodamientos), hidráulicas (succión, cavitación) o estructurales (base, resonancia). La secuencia correcta es síntoma → hipótesis de cavitación → evidencia → verificación, no una conclusión inmediata." },
 { code: "D4-04", title: "Rodamiento caliente en un motor-ventilador: ¿desbalance?", case: "La termografía de un conjunto motor-ventilador muestra temperatura elevada en el rodamiento del lado del acoplamiento. Alguien propone de inmediato \"debe ser desbalance del impulsor\" y sugiere desmontarlo para balancearlo.", prompt: "¿La temperatura elevada en un rodamiento confirma por sí sola un problema de desbalance? ¿Qué otras condiciones podrían producir el mismo síntoma?", lenses: ["Síntoma vs. modo de falla vs. causa", "Lubricación y contaminación", "Desalineación como alternativa", "Evidencia adicional antes de desmontar"], options: ["Desmontar el impulsor de inmediato para balancearlo, ya que la temperatura ya lo confirma.", "Investigar lubricación, alineación, montaje y condición del rodamiento antes de decidir una acción, ya que la temperatura elevada es evidencia, no diagnóstico.", "Ignorar el hallazgo mientras el ventilador siga moviendo aire con normalidad."], answer: 1, feedback: "Vibración o temperatura elevada no significan automáticamente desbalance. La pregunta correcta es: ¿qué evidencia demuestra que el desbalance —y no la lubricación, la alineación o el montaje— es el origen de la condición?" },
 { code: "D4-05", title: "Motor-Bomba P-204: ruido creciente, pero \"todavía no hay nada que cambiar\".", case: "Operaciones reporta que la bomba P-204 funciona, pero el ruido ha aumentado progresivamente en las últimas semanas. El historial muestra vibración con tendencia ascendente, temperatura del rodamiento superior a su comportamiento histórico, el elemento flexible reemplazado hace tres meses, lubricación reciente, y el motor sin evidencia eléctrica concluyente de falla.", prompt: "Con toda esta información reunida, ¿ya se puede ordenar el reemplazo de un componente? ¿Qué deberían hacer antes de decidir qué cambiar?", lenses: ["Tendencia vs. lectura aislada", "Múltiples hipótesis simultáneas", "Historial de reemplazo reciente", "Evidencia suficiente para sustentar una decisión"], options: ["Reemplazar de nuevo el elemento flexible, ya que fue lo último que se cambió y podría estar fallando otra vez.", "Reconocer que aún no existe información suficiente y establecer hipótesis —alineación, rodamiento, lubricación, acoplamiento, condición hidráulica— antes de decidir.", "Aumentar la frecuencia de lubricación como medida preventiva general sin más análisis."], answer: 1, feedback: "Diagnosticar no significa encontrar una explicación posible; significa construir evidencia suficiente para sustentar una decisión técnica. Una tendencia ascendente con múltiples hallazgos exige comparar hipótesis, no repetir el último cambio realizado." },
];

export default function DayFourExperience({ onBack, onProgressChange, resetToken }: { onBack: () => void; onProgressChange: (progress: number) => void; resetToken: number }) {
 const [tab, setTab] = useState<Tab>("overview");
 const [completed, setCompleted] = useState<DayFourSection[]>([]);
 const [debateAnswers, setDebateAnswers] = useState<Record<string, number>>({});

 function refreshDebateAnswers() { const saved = localStorage.getItem("integr-day4-debates"); setDebateAnswers(saved ? JSON.parse(saved) : {}); }
 useEffect(() => { try { const saved = localStorage.getItem("integr-day4-completed"); const next: DayFourSection[] = saved ? JSON.parse(saved) : []; setCompleted(next); onProgressChange(Math.round((next.length / 4) * 100)); } catch { localStorage.removeItem("integr-day4-completed"); } refreshDebateAnswers(); }, [onProgressChange]);
 useEffect(() => { if (resetToken) setTab("overview"); }, [resetToken]);

 const nav = (next: Tab) => { if (next === "overview") refreshDebateAnswers(); setTab(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
 const markDone = (id: DayFourSection) => { const next = completed.includes(id) ? completed.filter((item) => item !== id) : [...completed, id]; setCompleted(next); localStorage.setItem("integr-day4-completed", JSON.stringify(next)); onProgressChange(Math.round((next.length / 4) * 100)); };

 if (tab === "overview") return <DayFourLanding onOpen={nav} onBack={onBack} completed={completed} debateAnswers={Object.keys(debateAnswers).length} />;
 return <>
  <SectionNav active={tab} completed={completed} onSelect={nav} />
  {tab === "teoria" && <TheoryStudio dayLabel="DÍA 4" moduleLabel="MÓDULO IV" moduleTitle={<>Sistemas<br/>mecánicos</>} overline="TEORÍA INTERACTIVA · PRESENTACIÓN Y MANUAL" introTitle="Sistemas mecánicos, explicados visualmente" introCopy="Recorre la presentación del Módulo IV y consulta el manual completo cuando lo necesites." slides={theorySlides} sessionCount={3} pdfHref="/modulo-4-dia-4.pdf" pdfTitle="Módulo IV Día 4" pageCount={63} completed={completed.includes("teoria")} onDone={() => markDone("teoria")} checklistHref="/checklist-dia4.pdf" checklistLabel="Checklist de integración de evidencias" />}
  {tab === "video" && <VideoSlides overline="VIDEO-LECCIÓN" introTitle="Del síntoma a la causa raíz" introCopy="Reproduce el video completo del Módulo IV. Consulta la presentación y el manual en la sección de Teoría cuando quieras repasar un concepto." featureLabel="VIDEO PRINCIPAL · MÓDULO IV" featureTitle="El Detective Industrial" featureCopy="Sigue el caso guiado del Módulo IV: reunir evidencia, formular hipótesis y llegar a la causa raíz de una falla mecánica, igual que un detective investigando una escena." videoSrc="/el-detective-industrial.mp4" poster="/dia4-video-poster.jpg" videoAriaLabel="Video de lección El Detective Industrial del Módulo IV" completed={completed.includes("video")} onDone={() => markDone("video")} />}
  {tab === "practica" && <ScenarioSimulator scenarios={module4Scenarios} heroLabel="DETECTIVE MECÁNICO" heroTitle="Investiga antes de cambiar una pieza" heroCopy="Cinco casos del Módulo IV. En cada uno decides qué inspeccionar primero, correlacionas la evidencia y formulas la hipótesis mejor sustentada — como en el video de El Detective Industrial." moduleLabel="MÓDULO IV" storageKey="integr-day4-practica" completed={completed.includes("practica")} onComplete={() => !completed.includes("practica") && markDone("practica")} onBack={() => nav("overview")} />}
  {tab === "debate" && <DebateExperience debates={module4Debates} completed={completed.includes("debate")} onComplete={() => { if (!completed.includes("debate")) markDone("debate"); }} onBack={() => nav("overview")} moduleLabel="MÓDULO IV" storageKey="integr-day4-debates" />}
 </>;
}
