"use client";
import { useEffect, useState } from "react";
import DayThreeLanding, { type DayThreeSection } from "./DayThreeLanding";
import DebateExperience from "./DebateExperience";
import TheoryStudio from "./TheoryStudio";
import VideoSlides from "./VideoSlides";
import ScenarioSimulator, { type SimScenario } from "./ScenarioSimulator";
import { SectionNav, type Slide } from "./shared";

const theorySlides: Slide[] = [
 { src: "/slides/dia3/slide-01.jpg", alt: "Instrumentación y Seguridad — Portada del Módulo III" },
 { src: "/slides/dia3/slide-02.jpg", alt: "La medición como fundamento del diagnóstico" },
 { src: "/slides/dia3/slide-03.jpg", alt: "Voltímetro y Multímetro Digital" },
 { src: "/slides/dia3/slide-04.jpg", alt: "Amperímetro y Pinza Amperimétrica" },
 { src: "/slides/dia3/slide-05.jpg", alt: "Categorías CAT y la Inspección Previa del Instrumento" },
 { src: "/slides/dia3/slide-06.jpg", alt: "Termografía Infrarroja: Ver el Calor" },
 { src: "/slides/dia3/slide-07.jpg", alt: "ROJO ≠ FALLA" },
 { src: "/slides/dia3/slide-08.jpg", alt: "Multímetro vs. Megóhmetro" },
 { src: "/slides/dia3/slide-09.jpg", alt: "El Valor de la Tendencia" },
 { src: "/slides/dia3/slide-10.jpg", alt: "Choque Eléctrico y Arc Flash" },
 { src: "/slides/dia3/slide-11.jpg", alt: "Desenergizar No Es Solo Apagar el Interruptor" },
 { src: "/slides/dia3/slide-12.jpg", alt: "Cierre del Módulo III" },
];

type Tab = "overview" | DayThreeSection;

const module3Scenarios: SimScenario[] = [
 { code: "SIM3-01", title: "Inspección previa: puntas agrietadas", situation: "Antes de iniciar cualquier medición en un tablero, revisas visualmente tu multímetro y las puntas de prueba. Encuentras una grieta pequeña en el aislamiento de una de las puntas.", steps: [
   { prompt: "¿Qué haces con el instrumento?", options: ["Usarlo igual, la grieta es pequeña y no afecta la medición.", "Retirarlo de servicio hasta que sea reparado o reemplazado.", "Cubrir la grieta con cinta aislante y continuar.", "Usarlo solo para mediciones de bajo voltaje."], answer: 1, feedback: "OSHA establece que cuando un instrumento o sus accesorios presentan un defecto que puede representar un riesgo, deben retirarse de servicio hasta ser reparados y comprobados como seguros." },
   { prompt: "¿Qué revisarías además de las puntas antes de medir?", options: ["Solo que el instrumento encienda.", "Carcasa, selector, pantalla, terminales, categoría y tensión nominal.", "No hace falta revisar nada más si el instrumento enciende.", "Basta con revisar la marca del fabricante."], answer: 1, feedback: "La inspección previa incluye el instrumento (carcasa, selector, pantalla, terminales, categoría/tensión nominal) y puntas/cables (aislamiento, grietas, conectores)." },
   { prompt: "Con un instrumento ya verificado, ¿qué confirmas justo antes de conectar las puntas?", options: ["Que la función y el rango seleccionados correspondan a lo que vas a medir.", "Que el color del instrumento combine con el tablero.", "Que nadie te esté observando.", "Que el instrumento sea el más caro disponible."], answer: 0, feedback: "Antes de medir se confirma la configuración: función, AC/DC, rango y conexión correcta de las puntas." },
 ] },
 { code: "SIM3-02", title: "Categoría CAT para un tablero de 480 V", situation: "Te piden medir tensión en un tablero de distribución industrial de 480 V. Tienes disponibles dos multímetros: uno CAT II 600V y otro CAT III 600V.", steps: [
   { prompt: "¿Cuál usarías?", options: ["El CAT II, porque también soporta 600 V.", "El CAT III, porque el punto de medición corresponde a distribución/tablero.", "Cualquiera, la categoría no importa si el voltaje coincide.", "El que esté más cerca."], answer: 1, feedback: "La categoría CAT indica qué tan bien soporta el instrumento las sobretensiones transitorias del punto donde se mide, no solo el voltaje nominal. Tableros y distribución requieren CAT III como mínimo." },
   { prompt: "Un compañero dice: \"mejor usa uno CAT IV, siempre es mejor que CAT III\". ¿Estás de acuerdo?", options: ["Sí, CAT IV siempre es la opción más segura en cualquier punto.", "No, la categoría debe corresponder al punto de medición junto con la tensión nominal.", "No importa, ambas categorías son iguales.", "Solo si el instrumento es de una marca reconocida."], answer: 1, feedback: "Es un error común. La interpretación correcta combina categoría + tensión nominal + ubicación de la medición + procedimiento de seguridad, no \"más alto siempre es mejor\"." },
   { prompt: "Antes de conectar, ¿qué EPP consideras mínimo indispensable?", options: ["Ninguno, es solo una medición de tensión.", "El definido por la evaluación de riesgo y la etiqueta de Arc Flash del tablero.", "Solo lentes de sol.", "Cualquier guante de algodón."], answer: 1, feedback: "La selección de EPP se basa en la evaluación de riesgo (peligro → tarea → evaluación → procedimiento), no en suposiciones ni únicamente en el nivel de tensión." },
 ] },
 { code: "SIM3-03", title: "Motor con antecedentes de humedad", situation: "Un motor estuvo expuesto a una fuga de agua hace unos días. Antes de volver a energizarlo, mantenimiento quiere confirmar el estado de su aislamiento.", steps: [
   { prompt: "¿Qué instrumento corresponde?", options: ["Multímetro en función de resistencia.", "Megóhmetro.", "Pinza amperimétrica.", "Probador de tensión."], answer: 1, feedback: "El megóhmetro aplica una tensión DC de prueba y está diseñado específicamente para evaluar resistencias elevadas de aislamiento; el multímetro no sustituye esta prueba." },
   { prompt: "¿Qué debes verificar antes de aplicar la prueba?", options: ["Que el motor esté desenergizado y aislado conforme al procedimiento.", "Que el motor tenga el tanque de combustible lleno.", "Que sea de día.", "Nada en particular, el megóhmetro es seguro siempre."], answer: 0, feedback: "Antes de una prueba de aislamiento debe confirmarse que el equipo está en las condiciones eléctricas requeridas: identificar, desenergizar y aislar, verificar, y solo entonces conectar y probar." },
   { prompt: "Obtienes 410 MΩ. El historial muestra 850 MΩ en enero y una caída progresiva hasta hoy. ¿Cómo interpretas el resultado?", options: ["410 MΩ es un valor alto, así que el motor está perfecto.", "Existe un deterioro progresivo del aislamiento que merece investigación, aunque el valor aislado parezca aceptable.", "El dato es irrelevante sin más contexto.", "Debe reemplazarse el motor de inmediato sin más análisis."], answer: 1, feedback: "Una medición aislada es difícil de interpretar; la tendencia (850→720→570→410 MΩ) muestra un deterioro progresivo que sí amerita investigación." },
 ] },
 { code: "SIM3-04", title: "Termografía de rutina en un tablero", situation: "Durante una inspección termográfica programada, capturas la imagen de tres conexiones del mismo circuito trifásico bajo carga similar.", steps: [
   { prompt: "¿Qué instrumento estás usando?", options: ["Termómetro de contacto.", "Cámara termográfica.", "Megóhmetro.", "Multímetro."], answer: 1, feedback: "La cámara termográfica permite identificar diferencias térmicas sin contacto directo con la superficie inspeccionada." },
   { prompt: "La imagen muestra una zona en rojo intenso sobre una de las conexiones. ¿Qué concluyes de inmediato?", options: ["Que esa conexión tiene una falla confirmada porque se ve roja.", "Que existe una anomalía térmica que debe investigarse, porque el color depende de la paleta configurada.", "Que la cámara está descompuesta.", "Que debes apretar la conexión ahí mismo, con el circuito energizado."], answer: 1, feedback: "ROJO ≠ FALLA. Los colores dependen de la paleta y escala seleccionadas en el equipo; se requiere analizar temperatura real, carga, emisividad y condiciones comparables." },
   { prompt: "¿Qué otro factor podría estar afectando la lectura de temperatura sin que exista ninguna falla?", options: ["La emisividad de la superficie inspeccionada.", "El color de la ropa del técnico.", "La marca de la cámara.", "El día de la semana."], answer: 0, feedback: "La emisividad de la superficie (pintada, oxidada, metálica brillante) afecta la lectura; superficies de baja emisividad pueden generar reflexiones que distorsionan la temperatura aparente." },
 ] },
 { code: "SIM3-05", title: "Energía después de apagar el interruptor", situation: "Vas a intervenir un gabinete que incluye un variador de frecuencia (VFD). El interruptor principal ya está en posición OFF.", steps: [
   { prompt: "¿Puedes considerar el circuito seguro para trabajar?", options: ["Sí, el interruptor en OFF garantiza que no hay energía.", "No todavía: debe bloquearse/etiquetarse y verificarse con equipo de prueba antes de considerarlo desenergizado.", "Sí, si el LED del VFD está apagado.", "Sí, si pasan 5 minutos desde que se apagó."], answer: 1, feedback: "Interruptor en OFF no es igual a bloqueado/etiquetado/verificado. Los conductores no bloqueados conforme al procedimiento deben tratarse como energizados hasta verificar lo contrario." },
   { prompt: "Además de la energía eléctrica del interruptor, ¿qué otra fuente de energía debes considerar en un VFD?", options: ["Ninguna, un VFD no almacena energía.", "Los capacitores del bus DC, que pueden conservar tensión después de desconectar la alimentación.", "El ruido ambiental.", "El color del gabinete."], answer: 1, feedback: "Los VFD contienen capacitores en el bus DC que pueden mantener energía después de retirar la alimentación; siempre deben seguirse los tiempos y procedimientos del fabricante." },
   { prompt: "¿Cómo confirmas que ya es seguro tocar los componentes internos?", options: ["Asumiendo que ya pasó suficiente tiempo.", "Verificando ausencia de tensión con un instrumento de prueba adecuado y siguiendo el procedimiento del fabricante.", "Tocando brevemente con el dorso de la mano.", "Preguntándole a un compañero si él lo haría."], answer: 1, feedback: "Debe verificarse la ausencia de tensión con equipo de prueba apropiado, nunca asumirla ni comprobarla por contacto directo." },
 ] },
];

const module3Debates = [
 { code: "D3-01", title: "Corriente desigual entre las tres fases de un motor.", case: "Un técnico mide con pinza amperimétrica un motor trifásico: L1 = 18.2 A, L2 = 18.5 A y L3 = 26.7 A. La placa del motor no muestra daño visible y el equipo sigue operando con normalidad aparente.", prompt: "Debatan qué representa esta diferencia y qué deberían hacer antes de declarar una conclusión. ¿Basta la medición de corriente para diagnosticar la causa?", lenses: ["Evidencia vs. diagnóstico", "Correlación con tensión y carga", "Condición del devanado", "Investigación adicional necesaria"], options: ["Concluir de inmediato que el motor está dañado y programar su reemplazo.", "Registrar la desviación en L3 como evidencia inicial y correlacionarla con tensión de alimentación, carga mecánica, conexiones y protecciones antes de decidir.", "Ignorar la lectura porque el motor sigue funcionando sin detenerse."], answer: 1, feedback: "Medir identifica una condición; diagnosticar requiere explicar técnicamente esa condición con evidencia suficiente. Una corriente desigual entre fases es evidencia inicial, no una causa raíz confirmada." },
 { code: "D3-02", title: "Tres conexiones con distinta temperatura en la termografía.", case: "Una inspección termográfica de rutina en un sistema trifásico registra: L1 = 43 °C, L2 = 44 °C y L3 = 72 °C. La imagen muestra la zona de L3 en un color más intenso que las otras dos.", prompt: "¿El color más intenso de la imagen demuestra por sí solo que existe una falla en esa conexión? ¿Qué otros factores deben considerarse antes de intervenir?", lenses: ["Interpretación de color vs. temperatura real", "Emisividad de la superficie", "Condición de carga comparable", "Investigación técnica adicional"], options: ["Apretar de inmediato la conexión de L3 porque el color indica que está floja.", "Reconocer una anomalía térmica en L3 que requiere investigación —carga, emisividad, conexión, historial— antes de intervenir.", "Ignorar el hallazgo porque ninguna de las tres temperaturas supera los 100 °C."], answer: 1, feedback: "ROJO ≠ FALLA. Los colores dependen de la paleta y escala seleccionadas en la cámara. Una diferencia térmica real entre puntos comparables es evidencia que debe correlacionarse con carga, emisividad y condición de la conexión antes de intervenir." },
 { code: "D3-03", title: "¿Multímetro o megóhmetro para evaluar un motor sospechoso?", case: "Un motor presenta antecedentes de humedad y el equipo de mantenimiento necesita evaluar el estado de su aislamiento antes de volver a energizarlo. Alguien propone usar el multímetro en la función de resistencia porque 'de todos modos mide ohms'.", prompt: "Debatan si el multímetro es equivalente al megóhmetro para esta evaluación. ¿Qué diferencia técnica existe entre ambos instrumentos?", lenses: ["Tensión de prueba aplicada", "Rango de resistencia evaluado", "Propósito de diseño del instrumento", "Riesgo de un diagnóstico incompleto"], options: ["Usar el multímetro: si ambos miden resistencia, el resultado será equivalente.", "Usar el megóhmetro, que aplica una tensión DC de prueba y está diseñado para evaluar las resistencias elevadas propias del aislamiento eléctrico.", "No es necesario medir nada si el motor enciende al energizarlo brevemente."], answer: 1, feedback: "El multímetro realiza diagnóstico eléctrico general con resistencias convencionales; no sustituye una prueba de aislamiento. El megóhmetro aplica una tensión DC de prueba y está diseñado específicamente para evaluar resistencias elevadas de aislamiento en MΩ." },
 { code: "D3-04", title: "\"Es un tablero de 480 V, ya sé qué EPP necesito.\"", case: "Un técnico debe intervenir dos tableros distintos, ambos alimentados a 480 V. Asume que, al tener la misma tensión nominal, requieren exactamente el mismo nivel de protección contra Arc Flash.", prompt: "¿Es correcto decidir el EPP únicamente a partir del voltaje nominal? ¿Qué otros factores determinan la energía incidente de un arco eléctrico?", lenses: ["Corriente de cortocircuito disponible", "Tiempo de despeje de la protección", "Configuración del sistema", "Etiquetado y estudio de Arc Flash"], options: ["Sí: si el voltaje es igual, el EPP requerido también lo es.", "No: la energía incidente depende también de la corriente de cortocircuito disponible, el tiempo de despeje y la configuración del sistema; debe consultarse el estudio y la etiqueta de cada tablero.", "No es necesario EPP si el tablero se ve en buen estado físico."], answer: 1, feedback: "Baja o igual tensión no implica el mismo riesgo de Arc Flash. Dos tableros de 480 V pueden tener corrientes de cortocircuito y tiempos de despeje distintos. La selección del EPP debe basarse en la evaluación de riesgo y la etiqueta del equipo, no solo en el voltaje." },
 { code: "D3-05", title: "Motor M-204: evidencia suficiente para intervenir, pero no para decidir solo.", case: "Producción reporta que el motor extractor M-204 no arranca y pide revisión inmediata. El técnico encuentra el tablero energizado, una anomalía térmica en un rodamiento, una diferencia de corriente entre fases y determina que la condición excede su nivel de autorización actual.", prompt: "Con evidencia térmica y eléctrica ya reunida, ¿cuál es la decisión técnicamente correcta? ¿Seguir midiendo hasta encontrar la causa cuenta como buena práctica aquí?", lenses: ["Límite de autorización y calificación", "Valor de la evidencia ya reunida", "Riesgo de continuar sin autorización", "Escalamiento como decisión profesional"], options: ["Continuar midiendo hasta localizar la causa exacta, ya que existen suficientes evidencias reunidas.", "Detener la intervención y escalar conforme al procedimiento, documentando las evidencias obtenidas hasta ese punto.", "Reiniciar el motor para observar si el síntoma desaparece por sí solo."], answer: 1, feedback: "Reconocer que una condición excede el nivel de autorización propio no es falta de competencia: es la aplicación correcta del sistema de seguridad. Ninguna falla de producción justifica una intervención eléctrica sin control del riesgo." },
];

export default function DayThreeExperience({ onBack, onProgressChange, resetToken }: { onBack: () => void; onProgressChange: (progress: number) => void; resetToken: number }) {
 const [tab, setTab] = useState<Tab>("overview");
 const [completed, setCompleted] = useState<DayThreeSection[]>([]);
 const [debateAnswers, setDebateAnswers] = useState<Record<string, number>>({});

 function refreshDebateAnswers() { const saved = localStorage.getItem("integr-day3-debates"); setDebateAnswers(saved ? JSON.parse(saved) : {}); }
 useEffect(() => { try { const saved = localStorage.getItem("integr-day3-completed"); const next: DayThreeSection[] = saved ? JSON.parse(saved) : []; setCompleted(next); onProgressChange(Math.round((next.length / 4) * 100)); } catch { localStorage.removeItem("integr-day3-completed"); } refreshDebateAnswers(); }, [onProgressChange]);
 useEffect(() => { if (resetToken) setTab("overview"); }, [resetToken]);

 const nav = (next: Tab) => { if (next === "overview") refreshDebateAnswers(); setTab(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
 const markDone = (id: DayThreeSection) => { const next = completed.includes(id) ? completed.filter((item) => item !== id) : [...completed, id]; setCompleted(next); localStorage.setItem("integr-day3-completed", JSON.stringify(next)); onProgressChange(Math.round((next.length / 4) * 100)); };

 if (tab === "overview") return <DayThreeLanding onOpen={nav} onBack={onBack} completed={completed} debateAnswers={Object.keys(debateAnswers).length} />;
 return <>
  <SectionNav active={tab} completed={completed} onSelect={nav} />
  {tab === "teoria" && <TheoryStudio dayLabel="DÍA 3" moduleLabel="MÓDULO III" moduleTitle={<>Instrumentación<br/>y seguridad</>} overline="TEORÍA INTERACTIVA · PRESENTACIÓN Y MANUAL" introTitle="Instrumentación y seguridad, explicadas visualmente" introCopy="Recorre la presentación del Módulo III y consulta el manual completo cuando lo necesites." slides={theorySlides} sessionCount={3} pdfHref="/modulo-3-dia-3.pdf" pdfTitle="Módulo III Día 3" pageCount={29} completed={completed.includes("teoria")} onDone={() => markDone("teoria")} />}
  {tab === "video" && <VideoSlides overline="VIDEO-LECCIÓN" introTitle="De la medición a la decisión segura" introCopy="Reproduce el video completo del Módulo III. Consulta la presentación y el manual en la sección de Teoría cuando quieras repasar un concepto." featureLabel="VIDEO PRINCIPAL · MÓDULO III" featureTitle="Diagnóstico y Seguridad" featureCopy="Video específico del Día 3 para conectar la teoría de medición, diagnóstico y riesgo eléctrico con instrumentos y procedimientos reales." videoSrc="/diagnostico-y-seguridad.mp4" poster="/dia3-video-poster.jpg" videoAriaLabel="Video de lección Diagnóstico y Seguridad del Módulo III" completed={completed.includes("video")} onDone={() => markDone("video")} />}
  {tab === "practica" && <ScenarioSimulator scenarios={module3Scenarios} heroLabel="SIMULADOR TÉCNICO" heroTitle="Elige el instrumento y actúa seguro" heroCopy="Cinco casos del Módulo III. En cada uno decides el instrumento, la condición de seguridad y cómo interpretar el resultado — igual que en campo." moduleLabel="MÓDULO III" storageKey="integr-day3-practica" completed={completed.includes("practica")} onComplete={() => !completed.includes("practica") && markDone("practica")} onBack={() => nav("overview")} />}
  {tab === "debate" && <DebateExperience debates={module3Debates} completed={completed.includes("debate")} onComplete={() => { if (!completed.includes("debate")) markDone("debate"); }} onBack={() => nav("overview")} moduleLabel="MÓDULO III" storageKey="integr-day3-debates" />}
 </>;
}
