"use client";
import { useEffect, useState } from "react";
import DayTwoLanding, { type DayTwoSection } from "./DayTwoLanding";
import DebateExperience from "./DebateExperience";

type Tab="overview"|DayTwoSection;
const topics=[
 {title:"Arquitectura del sistema industrial",copy:"La energía sigue una ruta: suministro, transformación, distribución, protección, control y carga.",facts:["Fuente y tensión","Transformador","Tablero y MCC"]},
 {title:"Potencia y circuito de control",copy:"El circuito de potencia entrega energía al motor; el circuito de control decide cuándo y cómo debe operar.",facts:["Potencia","Control","Interlocks"]},
 {title:"Cómo leer un diagrama unifilar",copy:"Lee siempre de la fuente a la carga y, durante el diagnóstico, recorre el camino inverso para encontrar dónde se perdió la condición esperada.",facts:["Fuente → protección","Distribución → control","Control → carga"]},
 {title:"Riesgo eléctrico y autorización",copy:"Un equipo apagado no demuestra ausencia de tensión. Se requiere procedimiento, personal autorizado, análisis de riesgos y verificación aplicable.",facts:["Choque","Arco","Energía inesperada"]},
 {title:"Protecciones y diagnóstico",copy:"Un disparo es información, no diagnóstico. Diferencia sobrecarga, cortocircuito y falla a tierra antes de reenergizar.",facts:["Térmica","Magnética","I²R y calor"]}
];
const cases=["El motor no arranca y el HMI indica MOTOR NOT READY.","La banda consume 21.9 A en las tres fases y su placa indica 18 A.","Un breaker dispara después de varios minutos, no instantáneamente.","Una terminal registra 71 °C frente a otras de 39 °C y 40 °C.","Producción pide aumentar la capacidad de la protección para evitar paros."];
const module2Debates=cases.map((item,i)=>({code:`D2-0${i+1}`,title:item,case:item,prompt:"¿Qué evidencia y control de seguridad deben analizar antes de decidir?",lenses:["Fuente y protección","Evidencia medida","Riesgo de intervenir","Continuidad controlada"],options:["Seguir la ruta del diagrama, verificar seguridad y reunir evidencia.","Resetear o aumentar la protección para continuar produciendo.","Concluir que el motor está dañado sin revisar aguas arriba."],answer:0,feedback:"El diagnóstico debe seguir la ruta del sistema, consultar autorización y confirmar la hipótesis antes de intervenir."}));

export default function DayTwoExperience({onBack,onProgressChange}:{onBack:()=>void;onProgressChange:(progress:number)=>void}){
 const [tab,setTab]=useState<Tab>("overview"); const [topic,setTopic]=useState(0); const [manualOpen,setManualOpen]=useState(false); const [completed,setCompleted]=useState<DayTwoSection[]>([]);
 useEffect(()=>{try{const saved=localStorage.getItem("integr-day2-completed");const next:DayTwoSection[]=saved?JSON.parse(saved):[];setCompleted(next);onProgressChange(Math.round((next.length/4)*100))}catch{localStorage.removeItem("integr-day2-completed")}},[onProgressChange]);
 const nav=(next:Tab)=>{setTab(next);setManualOpen(false);window.scrollTo({top:0,behavior:"smooth"})};
 const markDone=(id:DayTwoSection)=>{const next=completed.includes(id)?completed.filter(item=>item!==id):[...completed,id];setCompleted(next);localStorage.setItem("integr-day2-completed",JSON.stringify(next));onProgressChange(Math.round((next.length/4)*100))};
 const nextSection:Record<Exclude<Tab,"overview">,Tab>={teoria:"video",video:"practica",practica:"debate",debate:"overview"};
 if(tab==="overview") return <DayTwoLanding onOpen={nav} onBack={onBack} completed={completed}/>;
 if(tab==="debate") return <DebateExperience debates={module2Debates} completed={completed.includes("debate")} onComplete={()=>{if(!completed.includes("debate"))markDone("debate");nav("overview")}} onBack={()=>nav("overview")} moduleLabel="MÓDULO II"/>;
 return <div className="page-content lesson-page day2-page"><header className="page-intro"><span className="big-index">{tab==="teoria"?"01":tab==="video"?"02":tab==="practica"?"03":"04"}</span><div className="page-intro-copy"><small>MÓDULO II · DÍA 2 · {tab.toUpperCase()}</small><h1>{tab==="teoria"?"Sistemas eléctricos industriales":tab==="video"?"Electricidad industrial":tab==="practica"?"Práctica en video":"Debate técnico"}</h1><p>El mismo formato de aprendizaje del Día 1, con contenidos específicos del Módulo II.</p></div><aside className="page-intro-meta"><span>ESTA SECCIÓN</span><b>{tab==="teoria"?"5 conceptos":tab==="video"?"Video + audio":tab==="practica"?"2 videos":"5 casos"}</b><small>Manual · observación · decisión</small></aside></header>
 <nav className="day2-tabs" role="tablist">{([["teoria","01","Teoría"],["video","02","Video-lección"],["practica","03","Práctica"],["debate","04","Debate"]] as const).map(([id,n,label])=><button key={id} className={tab===id?"active":""} onClick={()=>nav(id)}><span>{n}</span><b>{label}</b></button>)}</nav>
 {tab==="teoria"&&<><div className="theory-studio"><nav className="topic-list" aria-label="Capítulos del Módulo II">{topics.map((item,i)=><button key={item.title} className={topic===i?"active":""} onClick={()=>setTopic(i)}><span>{String(i+1).padStart(2,"0")}</span><div><small>MÓDULO II · PDF</small><b>{item.title}</b></div><i>→</i></button>)}</nav><article className="topic-stage accent-blue"><div className="topic-copy"><span>SISTEMAS ELÉCTRICOS INDUSTRIALES</span><small>CONCEPTO {topic+1} / {topics.length}</small><h2>{topics[topic].title}</h2><p>{topics[topic].copy}</p><div className="plain-language"><span>EN PALABRAS SIMPLES</span><p>Primero entiende el recorrido de la energía; después identifica qué elemento protege, controla o recibe la carga.</p></div><div className="topic-facts">{topics[topic].facts.map((f,i)=><div key={f}><span>{i+1}</span><b>{f}</b></div>)}</div></div><div className="theory-visual theory-process"><div className="diagnostic-process">{["Fuente","Protección","Distribución","Control","Carga"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></div><div className="topic-controls"><button disabled={!topic} onClick={()=>setTopic(topic-1)}>← Anterior</button><span><b>{topic+1}</b> / {topics.length}</span><button disabled={topic===topics.length-1} onClick={()=>setTopic(topic+1)}>Siguiente →</button></div></article></div><section className="manual-banner"><div className="manual-cover"><span>MÓDULO II</span><b>Sistemas eléctricos<br/>industriales</b><small>Manual completo · 43 páginas</small></div><div className="manual-summary"><span>DOCUMENTO OFICIAL DEL DÍA 2</span><h3>Consulta la teoría completa cuando la necesites</h3><p>Incluye arquitectura del sistema industrial, potencia y control, lectura de diagramas unifilares, riesgo eléctrico, protecciones y diagnóstico.</p><div><button className="primary" onClick={()=>setManualOpen(true)}>Leer dentro del curso <span>↗</span></button><a href="/modulo-2-dia-2.pdf" target="_blank">Abrir PDF en otra pestaña</a></div></div><div className="manual-stats"><div><b>05</b><span>Conceptos</span></div><div><b>43</b><span>Páginas</span></div><div><b>09h</b><span>Duración</span></div></div></section>{manualOpen&&<div className="manual-modal" role="dialog" aria-modal="true" aria-label="Manual Módulo II"><button className="modal-backdrop" onClick={()=>setManualOpen(false)} aria-label="Cerrar manual"/><div className="pdf-window"><header><div><span>MÓDULO II · DÍA 2</span><b>Sistemas eléctricos industriales</b></div><a href="/modulo-2-dia-2.pdf" target="_blank">Abrir aparte ↗</a><button onClick={()=>setManualOpen(false)} aria-label="Cerrar">×</button></header><iframe title="Módulo II Día 2" src="/modulo-2-dia-2.pdf#view=FitH"/></div></div>}</>}
 {tab==="video"&&<><section className="lesson-video-feature"><div className="lesson-video-copy"><span>VIDEO PRINCIPAL · MÓDULO II</span><h2>Electricidad industrial</h2><p>Video específico del Día 2 para conectar la teoría de sistemas eléctricos industriales con equipos, protecciones y recorridos reales.</p><div><b>▶ Video completo</b><small>Controles, audio y pantalla completa.</small></div></div><div className="lesson-video-frame"><video controls playsInline preload="metadata" poster="/day2-hero.png" aria-label="Video de Electricidad Industrial del Módulo II"><source src="/electricidad-industrial.mp4" type="video/mp4"/></video></div></section><section className="scene-learning"><div><span>IDEA CLAVE</span><b>La falla puede originarse aguas arriba del motor.</b></div><div><span>RUTA</span><p>Fuente → protección → MCC → VFD → motor.</p></div><div><span>PIENSA</span><p>¿Qué verificarías antes de abrir el gabinete?</p></div></section></>}
 {tab==="practica"&&<section className="practice-experience practice-videos-only"><section className="practice-video-library" aria-labelledby="practice-video-title"><header><div><span>03 · PRÁCTICA EN VIDEO</span><h2 id="practice-video-title">Lectura de un diagrama unifilar</h2></div><p>Observa los dos procedimientos y pausa cada ejemplo para reconocer la fuente, las protecciones, el control y la carga.</p></header><div className="practice-video-grid"><article><div className="practice-youtube"><iframe src="https://www.youtube-nocookie.com/embed/iRyfjmfcvBQ" title="Cómo leer un diagrama unifilar correctamente" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="practice-video-copy"><span>VIDEO PRINCIPAL · MÁS CAPACITACIÓN</span><h3>Cómo leer un diagrama unifilar correctamente</h3><p>Reconoce materiales, símbolos y el recorrido general de la energía.</p><a href="https://www.youtube.com/watch?v=iRyfjmfcvBQ" target="_blank" rel="noreferrer">Abrir en YouTube ↗</a></div></article><article><div className="practice-youtube"><iframe src="https://www.youtube-nocookie.com/embed/eqJaiEskVj0" title="Diagrama unifilar eléctrico paso a paso" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="practice-video-copy"><span>VIDEO DE REFUERZO · INGE IRVING</span><h3>Diagrama unifilar eléctrico paso a paso</h3><p>Identifica qué elemento alimenta, protege, controla o recibe la energía.</p><a href="https://www.youtube.com/watch?v=eqJaiEskVj0" target="_blank" rel="noreferrer">Abrir en YouTube ↗</a></div></article></div></section></section>}
 {tab==="debate"&&<section className="debate-experience"><header className="debate-header"><span>04 · DEBATE TÉCNICO</span><h1>Caso {caseIndex+1} de 5</h1><p>Primero analiza el caso; después elige la respuesta técnica.</p></header><article className="debate-case"><span>CASO</span><h2>{cases[caseIndex]}</h2><p>¿Qué decisión tomarías y qué evidencia consultarías antes de intervenir?</p></article><div className="debate-options">{["Seguir la ruta del diagrama, verificar seguridad y reunir evidencia.","Resetear o aumentar la protección para continuar produciendo.","Concluir que el motor está dañado sin revisar aguas arriba."].map((x,i)=><button key={x} onClick={()=>setChoice(i)} className={choice===i?(i===0?"correct":"wrong"):""}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div><div className="case-nav"><button disabled={!caseIndex} onClick={()=>{setCaseIndex(caseIndex-1);setChoice(null)}}>← Anterior</button><button className="primary" onClick={()=>{setCaseIndex((caseIndex+1)%5);setChoice(null)}}>Siguiente caso →</button></div></section>}
 <div className="completion-bar"><div><span>{completed.includes(tab)?"✓":"○"}</span><p><b>{completed.includes(tab)?"Etapa completada":"Completa esta etapa"}</b><small>Tu avance del Día 2 se guarda automáticamente.</small></p></div><div><button onClick={()=>markDone(tab)}>{completed.includes(tab)?"Marcar como pendiente":"Marcar como completada"}</button><button className="primary" onClick={()=>nav(nextSection[tab])}>Siguiente etapa →</button></div></div>
 <button className="day2-back" onClick={()=>nav("overview")}>← Volver al resumen del Día 2</button></div>;
}
