"use client";
import { useState } from "react";
import DayTwoLanding from "./DayTwoLanding";

type Tab = "overview" | "teoria" | "video" | "practica" | "debate";
const cases = [
  {title:"El motor no arranca", text:"El HMI indica MOTOR NOT READY. La ruta del unifilar es 480 V → MCC-02 → CB-08 → VFD-08 → motor M-204.", ask:"¿Dónde comenzarías y qué verificarías antes de abrir el gabinete?", options:["Ir directo al motor y cambiarlo","Seguir fuente → protección → control → carga, con autorización y verificación","Resetear el VFD sin consultar el diagrama"], answer:1},
  {title:"El breaker vuelve a disparar", text:"Una banda de 460 V consume 21.9 A en las tres fases; su placa indica 18 A y el operador reporta que se escucha pesada.", ask:"¿Qué hipótesis tiene más evidencia?", options:["Aumentar el breaker","Sobrecarga mecánica que debe investigarse","Ignorar el disparo porque la banda aún gira"], answer:1},
  {title:"¿Sobrecarga o cortocircuito?", text:"Una protección actúa después de varios minutos de operación estable. No hay conductor quemado visible, pero la corriente creció gradualmente.", ask:"¿Qué diferencia guía el diagnóstico?", options:["Sobrecarga: corriente superior sostenida; cortocircuito: trayectoria de muy baja impedancia y respuesta rápida","Son exactamente lo mismo","El voltaje nominal decide por sí solo"], answer:0},
  {title:"La terminal caliente", text:"En tres conexiones similares se observan 39 °C, 40 °C y 71 °C. La máquina todavía funciona.", ask:"¿Qué representa correctamente la termografía?", options:["Diagnóstico definitivo de la causa","Una anomalía que debe compararse, medir y verificar","Permiso para apretar la terminal energizada"], answer:1},
  {title:"La protección no se aumenta", text:"Producción pide cambiar una protección por otra de mayor capacidad porque dispara varias veces durante el turno.", ask:"¿Cuál es la decisión técnica?", options:["Cambiarla para evitar paros","Investigar causa, coordinación, carga e historial antes de reenergizar","Puenteearla temporalmente"], answer:1}
];

export default function DayTwoExperience({ onBack }: { onBack:()=>void }) {
 const [tab,setTab]=useState<Tab>("overview"); const [caseIndex,setCaseIndex]=useState(0); const [choice,setChoice]=useState<number|null>(null); const [sound,setSound]=useState(true);
 const speak=()=>{if(!sound||!("speechSynthesis" in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(tab==="teoria"?"Sistemas eléctricos industriales. Sigue la energía desde la fuente hasta la carga.":tab==="practica"?"Práctica guiada. Lee el diagrama unifilar, identifica protecciones y formula una ruta segura de diagnóstico.":c.title);u.lang="es-MX";u.rate=.92;speechSynthesis.speak(u)};
 const nav=(next:Tab)=>{setTab(next);setChoice(null);}; const c=cases[caseIndex];
 if(tab==="overview") return <DayTwoLanding onOpen={nav} onBack={onBack}/>;
 return <div className="page-content day2-page">
  <header className="page-intro day2-intro"><span className="big-index">02</span><div className="page-intro-copy"><small>MÓDULO II · DÍA 2 · 9 HORAS</small><h1>Sistemas eléctricos <em>industriales</em></h1><p>Comprende cómo llega, se protege y se diagnostica la energía antes de intervenir una máquina.</p></div><aside className="page-intro-meta"><span>RUTA DEL DÍA</span><b>4 experiencias</b><small>Teoría · video · práctica · debate</small><button className="day2-audio" onClick={()=>{setSound(!sound);speak()}}>{sound?"▶ Escuchar":"🔇 Audio apagado"}</button></aside></header>
  <div className="day2-tabs" role="tablist">{([["teoria","01","Teoría"],["video","02","Video-lección"],["practica","03","Práctica"],["debate","04","Debate"]] as const).map(([id,n,label])=><button key={id} className={tab===id?"active":""} onClick={()=>nav(id)}><span>{n}</span><b>{label}</b></button>)}</div>
  {tab==="teoria"&&<section className="day2-card theory-card"><div className="card-kicker">MANUAL OFICIAL · 43 PÁGINAS</div><h2>Del suministro a la carga</h2><p>El manual explica la distribución industrial, transformadores, tableros y MCC; diferencia potencia y control; identifica riesgos; y propone leer el unifilar desde la fuente hasta la carga.</p><div className="concept-grid">{["Fuente y niveles de tensión","Transformación y distribución","MCC, protecciones y cargas","Potencia vs. control","Riesgos y trabajo seguro","Ruta de diagnóstico"].map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b><small>{["¿De dónde viene la energía?","¿Qué tensión entrega el transformador?","¿Qué protege cada dispositivo?","¿Qué señal ordena al motor?","¿Es seguro continuar?","¿Qué evidencia confirma la causa?"][i]}</small></article>)}</div><div className="flow-strip"><b>FUENTE</b><i>→</i><b>PROTECCIÓN</b><i>→</i><b>DISTRIBUCIÓN</b><i>→</i><b>CONTROL</b><i>→</i><b>CARGA</b></div><a className="primary" href="/modulo-2-dia-2.pdf" target="_blank">Abrir PDF completo ↗</a></section>}
  {tab==="video"&&<section className="day2-card video-card"><div><div className="card-kicker">VIDEO DE LA LECCIÓN</div><h2>Sistemas electromecánicos</h2><p>Video corregido del Día 1 y disponible como introducción visual para conectar fundamentos con equipos reales.</p></div><video controls playsInline preload="metadata" poster="/og-professional.png"><source src="/sistemas-electromecanicos.mp4" type="video/mp4"/></video><div className="video-note">▶ Usa controles, audio y pantalla completa del reproductor.</div></section>}
  {tab==="practica"&&<section className="day2-card practice-card"><div className="card-kicker">PRÁCTICA GUIADA · SIN INTERVENCIÓN ENERGIZADA</div><h2>Lee el unifilar y encuentra la ruta de falla</h2><p>Observa cómo se interpreta un diagrama unifilar. Pausa el video para señalar fuente, transformador, protección, MCC, VFD y motor; después recorre la ruta en sentido inverso.</p><div className="youtube-wrap"><iframe src="https://www.youtube.com/embed/iRyfjmfcvBQ" title="Cómo leer un diagrama unifilar correctamente" loading="lazy" allowFullScreen/></div><div className="practice-steps">{["Identifica la fuente y la tensión","Marca protecciones y puntos de aislamiento","Sigue el alimentador hasta la carga","Escribe una hipótesis y qué evidencia falta"].map((s,i)=><div key={s}><span>{i+1}</span><b>{s}</b></div>)}</div><a className="text-link" href="https://www.youtube.com/watch?v=iRyfjmfcvBQ" target="_blank" rel="noreferrer">Abrir video en YouTube ↗</a></section>}
  {tab==="debate"&&<section className="day2-card debate-card"><div className="card-kicker">DEBATE TÉCNICO · CASO {String(caseIndex+1).padStart(2,"0")} / 05</div><h2>{c.title}</h2><div className="case-box"><span>CASO</span><p>{c.text}</p><strong>{c.ask}</strong></div><div className="debate-options">{c.options.map((o,i)=><button key={o} className={choice===i?i===c.answer?"correct":"wrong":""} disabled={choice!==null} onClick={()=>setChoice(i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div>{choice!==null&&<div className={`feedback ${choice===c.answer?"ok":"no"}`}>{choice===c.answer?"✓ Criterio correcto":"Revisa la secuencia"}<p>{choice===c.answer?"La respuesta prioriza seguridad, evidencia y método antes de intervenir.":"El caso exige consultar el diagrama, evaluar riesgos y confirmar la hipótesis; no ocultar el síntoma."}</p></div>}<div className="case-nav"><button onClick={()=>{setCaseIndex(Math.max(0,caseIndex-1));setChoice(null)}} disabled={caseIndex===0}>← Anterior</button><button className="primary" onClick={()=>{setCaseIndex((caseIndex+1)%cases.length);setChoice(null)}}>Siguiente caso →</button></div></section>}
  <button className="day2-back" onClick={onBack}>← Volver al resumen del Día 1</button>
 </div>;
}
