"use client";
import { useState } from "react";
import DayTwoLanding from "./DayTwoLanding";
import DebateExperience from "./DebateExperience";

type Tab="overview"|"teoria"|"video"|"practica"|"debate";
const topics=[
 {title:"Arquitectura del sistema industrial",copy:"La energía sigue una ruta: suministro, transformación, distribución, protección, control y carga.",facts:["Fuente y tensión","Transformador","Tablero y MCC"]},
 {title:"Potencia y circuito de control",copy:"El circuito de potencia entrega energía al motor; el circuito de control decide cuándo y cómo debe operar.",facts:["Potencia","Control","Interlocks"]},
 {title:"Cómo leer un diagrama unifilar",copy:"Lee siempre de la fuente a la carga y, durante el diagnóstico, recorre el camino inverso para encontrar dónde se perdió la condición esperada.",facts:["Fuente → protección","Distribución → control","Control → carga"]},
 {title:"Riesgo eléctrico y autorización",copy:"Un equipo apagado no demuestra ausencia de tensión. Se requiere procedimiento, personal autorizado, análisis de riesgos y verificación aplicable.",facts:["Choque","Arco","Energía inesperada"]},
 {title:"Protecciones y diagnóstico",copy:"Un disparo es información, no diagnóstico. Diferencia sobrecarga, cortocircuito y falla a tierra antes de reenergizar.",facts:["Térmica","Magnética","I²R y calor"]}
];
const cases=["El motor no arranca y el HMI indica MOTOR NOT READY.","La banda consume 21.9 A en las tres fases y su placa indica 18 A.","Un breaker dispara después de varios minutos, no instantáneamente.","Una terminal registra 71 °C frente a otras de 39 °C y 40 °C.","Producción pide aumentar la capacidad de la protección para evitar paros."];
const module2Debates=cases.map((item,i)=>({code:`D2-0${i+1}`,title:item,case:item,prompt:"¿Qué evidencia y control de seguridad deben analizar antes de decidir?",lenses:["Fuente y protección","Evidencia medida","Riesgo de intervenir","Continuidad controlada"],options:["Seguir la ruta del diagrama, verificar seguridad y reunir evidencia.","Resetear o aumentar la protección para continuar produciendo.","Concluir que el motor está dañado sin revisar aguas arriba."],answer:0,feedback:"El diagnóstico debe seguir la ruta del sistema, consultar autorización y confirmar la hipótesis antes de intervenir."}));

export default function DayTwoExperience({onBack}:{onBack:()=>void}){
 const [tab,setTab]=useState<Tab>("overview"); const [topic,setTopic]=useState(0); const [caseIndex,setCaseIndex]=useState(0); const [choice,setChoice]=useState<number|null>(null); const [step,setStep]=useState(0);
 const nav=(next:Tab)=>{setTab(next);setChoice(null);setStep(0)};
 if(tab==="overview") return <DayTwoLanding onOpen={nav} onBack={onBack}/>;
 if(tab==="debate") return <DebateExperience debates={module2Debates} completed={false} onComplete={()=>nav("overview")} onBack={()=>nav("overview")} moduleLabel="MÓDULO II"/>;
 return <div className="page-content lesson-page day2-page"><header className="page-intro"><span className="big-index">{tab==="teoria"?"01":tab==="video"?"02":tab==="practica"?"03":"04"}</span><div className="page-intro-copy"><small>MÓDULO II · DÍA 2 · {tab.toUpperCase()}</small><h1>{tab==="teoria"?"Sistemas eléctricos industriales":tab==="video"?"Sistemas electromecánicos":tab==="practica"?"Práctica de diagnóstico":"Debate técnico"}</h1><p>El mismo formato de aprendizaje del Día 1, con contenidos específicos del Módulo II.</p></div><aside className="page-intro-meta"><span>ESTA SECCIÓN</span><b>{tab==="teoria"?"5 conceptos":tab==="video"?"Video + audio":tab==="practica"?"4 pasos":"5 casos"}</b><small>Manual · observación · decisión</small></aside></header>
 <nav className="day2-tabs" role="tablist">{([["teoria","01","Teoría"],["video","02","Video-lección"],["practica","03","Práctica"],["debate","04","Debate"]] as const).map(([id,n,label])=><button key={id} className={tab===id?"active":""} onClick={()=>nav(id)}><span>{n}</span><b>{label}</b></button>)}</nav>
 {tab==="teoria"&&<div className="theory-studio"><nav className="topic-list" aria-label="Capítulos del Módulo II">{topics.map((item,i)=><button key={item.title} className={topic===i?"active":""} onClick={()=>setTopic(i)}><span>{String(i+1).padStart(2,"0")}</span><div><small>MÓDULO II · PDF</small><b>{item.title}</b></div><i>→</i></button>)}</nav><article className="topic-stage accent-blue"><div className="topic-copy"><span>SISTEMAS ELÉCTRICOS INDUSTRIALES</span><small>CONCEPTO {topic+1} / {topics.length}</small><h2>{topics[topic].title}</h2><p>{topics[topic].copy}</p><div className="plain-language"><span>EN PALABRAS SIMPLES</span><p>Primero entiende el recorrido de la energía; después identifica qué elemento protege, controla o recibe la carga.</p></div><div className="topic-facts">{topics[topic].facts.map((f,i)=><div key={f}><span>{i+1}</span><b>{f}</b></div>)}</div></div><div className="theory-visual theory-process"><div className="diagnostic-process">{["Fuente","Protección","Distribución","Control","Carga"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></div><div className="topic-controls"><button disabled={!topic} onClick={()=>setTopic(topic-1)}>← Anterior</button><span><b>{topic+1}</b> / {topics.length}</span><button disabled={topic===topics.length-1} onClick={()=>setTopic(topic+1)}>Siguiente →</button></div></article></div>}
 {tab==="video"&&<><section className="lesson-video-feature"><div className="lesson-video-copy"><span>VIDEO PRINCIPAL · MÓDULO II</span><h2>Sistemas electromecánicos</h2><p>Video específico del Día 2 para conectar la teoría de sistemas eléctricos industriales con equipos y recorridos reales.</p><div><b>▶ Video completo</b><small>Controles, audio y pantalla completa.</small></div></div><div className="lesson-video-frame"><video controls playsInline preload="metadata" poster="/og-professional.png" aria-label="Video del Módulo II"><source src="/sistemas-electromecanicos.mp4" type="video/mp4"/></video></div></section><section className="scene-learning"><div><span>IDEA CLAVE</span><b>La falla puede originarse aguas arriba del motor.</b></div><div><span>RUTA</span><p>Fuente → protección → MCC → VFD → motor.</p></div><div><span>PIENSA</span><p>¿Qué verificarías antes de abrir el gabinete?</p></div></section></>}
 {tab==="practica"&&<section className="practice-experience"><header className="practice-experience-head"><div><span>03 · PRÁCTICA GUIADA</span><h1>Lectura de un diagrama unifilar</h1><p>Comprende, observa, sigue la ruta y formula una hipótesis.</p></div><div className="practice-view-tools"><button onClick={()=>speechSynthesis?.speak(new SpeechSynthesisUtterance("Lee el diagrama desde la fuente hasta la carga."))}>▶ Escuchar</button><button onClick={()=>document.documentElement.requestFullscreen?.()}>□ Pantalla completa</button></div></header><div className="practice-progress"><span style={{width:`${((step+1)/4)*100}%`}}/><b>Paso {step+1} de 4</b></div><div className="practice-layout"><aside className="lab-menu"><span>RUTA DE PRÁCTICA</span>{["Identificar fuente y tensión","Ubicar protecciones y MCC","Seguir control hasta la carga","Formular hipótesis segura"].map((x,i)=><button key={x} className={step===i?"active":""} onClick={()=>setStep(i)}><i>{i+1}</i><div><small>PASO {i+1}</small><b>{x}</b></div><em>→</em></button>)}</aside><main className="practice-main"><div className="practice-scene"><span className="scene-label">PASO {step+1} · OBSERVA ANTES DE INTERVENIR</span><h2>{["¿De dónde llega la energía?","¿Qué dispositivo protege el circuito?","¿Cómo llega la orden al motor?","¿Qué evidencia falta para confirmar la causa?"][step]}</h2><p>{["Marca fuente, tensión y transformador en el diagrama.","Ubica interruptor principal, protección derivada y MCC.","Diferencia potencia, control, VFD y motor.","Escribe una hipótesis y las verificaciones autorizadas."][step]}</p><div className="simple-card"><span>REGLA DE SEGURIDAD</span><p>No supongas ausencia de tensión. Consulta procedimiento, autorización y control de energías peligrosas.</p></div></div><footer className="practice-presenter-controls"><button disabled={!step} onClick={()=>setStep(step-1)}>← Anterior</button><div><span>MÓDULO II</span><b>Ruta de diagnóstico</b><small>Avanza en orden</small></div><button className="next" disabled={step===3} onClick={()=>setStep(step+1)}>Siguiente →</button></footer></main></div></section>}
 {tab==="debate"&&<section className="debate-experience"><header className="debate-header"><span>04 · DEBATE TÉCNICO</span><h1>Caso {caseIndex+1} de 5</h1><p>Primero analiza el caso; después elige la respuesta técnica.</p></header><article className="debate-case"><span>CASO</span><h2>{cases[caseIndex]}</h2><p>¿Qué decisión tomarías y qué evidencia consultarías antes de intervenir?</p></article><div className="debate-options">{["Seguir la ruta del diagrama, verificar seguridad y reunir evidencia.","Resetear o aumentar la protección para continuar produciendo.","Concluir que el motor está dañado sin revisar aguas arriba."].map((x,i)=><button key={x} onClick={()=>setChoice(i)} className={choice===i?(i===0?"correct":"wrong"):""}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div><div className="case-nav"><button disabled={!caseIndex} onClick={()=>{setCaseIndex(caseIndex-1);setChoice(null)}}>← Anterior</button><button className="primary" onClick={()=>{setCaseIndex((caseIndex+1)%5);setChoice(null)}}>Siguiente caso →</button></div></section>}
 <button className="day2-back" onClick={()=>nav("overview")}>← Volver al resumen del Día 2</button></div>;
}
